apiVersion: v1
kind: Pod
metadata:
  name: nodejs-simple-pod
  labels:
    component: web-server
spec:
  containers:
    - name: web-server
      image: nlapshin/nodejs-simple-k8s
      ports:
        - containerPort: 4000
