apiVersion: v1
kind: Service
metadata:
  name: nodejs-simple-service
spec:
  selector:
    component: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
